const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('./ui/node_modules/jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const dom=new JSDOM('<!doctype html><body></body>',{runScripts:'outside-only',pretendToBeVisual:true});
const {window}=dom, subscribers=new Map(), sent=[];
let poll;
window.setInterval=fn=>{poll=fn;return 1;};
window.__okdevBridge={ready:true,subscribe:(type,fn)=>subscribers.set(type,fn),unsubscribe:()=>{},onReady:fn=>fn(),send:value=>sent.push(value)};
window.eval(read('Pengu Loader/plugins/OKDEV-Guide/index.js'));
const host=window.document.getElementById('okdev-guide-widget'),root=host.shadowRoot;
assert.ok(host.hidden);
const data={type:'guide-state',enabled:false,hotkey:'Ctrl+Shift+B',guide:{phase:'ChampSelect',pick:null}};
subscribers.get('guide-state')(data);assert.equal(host.hidden,false);
root.querySelector('.trigger').click();assert.equal(root.querySelector('.panel').hidden,false);
assert.equal(root.querySelector('.show').disabled,true);
root.querySelector('input').click();assert.equal(sent.at(-1).type,'guide-toggle');assert.equal(sent.at(-1).enabled,true);
data.enabled=true;data.guide.pick={champion:{id:11,name:'Master Yi'},role_label:'Orman'};
subscribers.get('guide-state')(data);assert.equal(root.querySelector('.show').disabled,false);
assert.match(root.querySelector('.trigger').textContent,/Master Yi/);
root.querySelector('.show').click();assert.equal(sent.at(-1).type,'guide-show');
subscribers.get('phase-change')({phase:'InProgress'});assert.equal(host.hidden,true);
window.__okdevBridge.ready=false;poll();assert.equal(host.hidden,true);
window.close();

const guide=new JSDOM('<!doctype html><body><h3>runes</h3><h3>items</h3><h3>ability order</h3></body>',{url:'https://mobalytics.gg/lol/champions/masteryi/build/jungle',runScripts:'outside-only'});
let tick,scrolled=[];
guide.window.setInterval=fn=>{tick=fn;return 1;};
guide.window.HTMLElement.prototype.scrollIntoView=function(){scrolled.push(this.textContent);};
guide.window.eval(read('hub/web/guide.js'));
const nav=guide.window.document.getElementById('okdev-guide-navigation').shadowRoot;
tick();assert.equal(scrolled.at(-1),'runes');
nav.querySelectorAll('button')[1].click();assert.equal(scrolled.at(-1),'items');
nav.querySelectorAll('button')[2].click();assert.equal(scrolled.at(-1),'ability order');
guide.window.document.querySelector('h3').textContent='ARAM runes';
nav.querySelectorAll('button')[0].click();assert.equal(scrolled.at(-1),'ARAM runes');
guide.window.OKDEV_GUIDE_HOTKEY='Alt+B';guide.window.eval(read('hub/web/guide.js'));
assert.equal(guide.window.document.querySelectorAll('#okdev-guide-navigation').length,1);
assert.equal(nav.querySelector('.key').textContent,'Alt+B');
guide.window.close();
console.log('Guide plugin and remote-page navigation passed: disabled/enabled states, champion display, manual show, gameplay hiding, disconnect, rune/item/ability section navigation.');
